# Generated by Django 3.2 on 2022-07-18 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20220717_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag2bookmark',
            name='is_linked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag2bookmark',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag2post',
            name='is_linked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag2post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
