# Generated by Django 3.2 on 2022-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20220724_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='bookmark',
            field=models.ManyToManyField(to='notes.Bookmark'),
        ),
    ]
