# Generated by Django 3.2 on 2022-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20220725_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='notes.Tag'),
        ),
    ]
