# Generated by Django 3.2 on 2022-07-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20220725_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='notes.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='notes.Tag'),
        ),
    ]
