version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - notes-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
    depends_on:
      - db

volumes:
  notes-db: